apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: connectivitydomains.cnns.cisco.com
spec:
  group: cnns.cisco.com
  names:
    kind: ConnectivityDomain
    listKind: ConnectivityDomainList
    plural: connectivitydomains
    singular: connectivitydomain
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ConnectivityDomain is the Schema for the connectivitydomains API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ConnectivityDomainSpec defines the desired state of ConnectivityDomain
          properties:
            fqdn:
              description: FQDN is the domain name under which network services controlled
                by the CNNS-NSR will be registered with
              minLength: 1
              type: string
            insecure:
              description: Insecure specifies whether future connections will be done
                using a secure connection
              type: string
            ipam:
              description: Specifies the addressing for the NSEs that will register
              properties:
                prefixPool:
                  description: Specify the CIDR of the Connectivity Domain
                  type: string
                routes:
                  description: Specify routes to be added to the Connectivity Domain
                    here
                  items:
                    type: string
                  type: array
              required:
                - prefixPool
              type: object
            size:
              description: Size is the size of the deployment
              format: int32
              minimum: 1
              type: integer
          required:
            - fqdn
            - ipam
          type: object
        status:
          description: ConnectivityDomainStatus defines the observed state of ConnectivityDomain
          properties:
            nsr:
              description: Represents meta information related to the NSR deployment
              properties:
                deployment:
                  description: Deployment is the NSR deployment that creates the NSR
                  type: string
                pods:
                  description: Pods are the names of the Connectivity Domains NSR
                    pods
                  items:
                    type: string
                  type: array
                role:
                  description: Role is the NSR role
                  type: string
                roleBinding:
                  description: Role Binding is the NSR role binding
                  type: string
                service:
                  description: Service is the service created to connect to the NSR
                  type: string
                serviceAccount:
                  description: Service Account is the NSR service account
                  type: string
              type: object
          required:
            - nsr
          type: object
      type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
