kind: ConfigMap
apiVersion: v1
metadata:
  name: connectivity-domain-configmap
  namespace: {{.Release.Namespace}}
data:
  config.yaml: |
    nsrType: {{.Values.nsr.type}}
    registry: {{.Values.nsr.registry}}
    org: {{.Values.nsr.org}}
    tag: {{.Values.nsr.tag}}
    pullPolicy: {{.Values.nsr.pullPolicy}}
    label: {{.Values.label}}
    nodeName: "master"
    serviceType: {{.Values.nsr.serviceType}}
    publicNsrPort: {{.Values.nsr.publicPort}}
    ipam:
      etcdAddresses:
        - {{.Values.ipam.etcdAddress}}
      leaseTimeout: {{.Values.ipam.leaseTimeout}}
      leaseCheckPeriod: {{.Values.ipam.leaseCheckPeriod}}
      nodePort: {{.Values.ipam.nodePort}}
