kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: connectivity-domain-operator
subjects:
- kind: ServiceAccount
  name: connectivity-domain-operator
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: connectivity-domain-operator
  apiGroup: rbac.authorization.k8s.io
