apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: nse-discovery-sa
  namespace: nsm-system
rules:
- apiGroups: ["networkservicemesh.io"]
  resources: ["networkserviceendpoints"]
  verbs: ["create", "get", "list", "watch"]

